base_url: "http://books.toscrape.com/"
selectors:
  name: "h3 a"
  price: "p.price_color"
  image_path: "div.image_container img"
  rating: "p.star-rating"
  availability: "p.instock.availability"
  details_link: "h3 a"
